### ISSUE TITLE
~~Adding LICENSE file~~

### ISSUE THREAD

**Issue by Mister-Hope** [bernd-wechner/Copy-with-Style#4]
~~It would be great if you can add a license file so other users know how to user your code.~~

A standard LICENSE file should be named `LICENSE`, without the `.md` extension.

**Comment by bernd-wechner** [comment]
Oh, I see. But github supports both:

https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

(step 3 in that document). And .md means if I edit it, it opens in my Markdown editor. That said, I can't see much need for that, there's a one-off edit to put the year imprint as top line I think. Which was done.

The View license link on the repo works and displays it. So is there a good reason to lose the .md?

**Comment by Mister-Hope** [comment]
Emm, node ecosystem suggests LICENSE. I realized GitHub supports it once I opened it. You can close this issue as it's not necessary.

I opened this because some of my tools are telling me this package does not have license. Then I found the one with md

**Comment by bernd-wechner** [comment]
Happy to strip the .md if it helps packaging.
